export enum ENDPOINTS {
  PROFILE = "/auth/me",
  REFRESH_TOKEN = "/auth/refresh",
  LOGIN = "/auth/email/login",
  REGISTER = "/auth/email/register",
  RESET_PASSWORD = "/auth/reset/password",
  FORGOT_PASSWORD = "/auth/forgot/password",
  UPLOAD = "/files/upload",
  PRODUCTS = "/products",
  CATEGORIES = "/categories",
  ORDERS = "/orders",
  ORDER = "/orders/:id",
  CART = "/cart",
  CHECKOUT = "/checkout",
}
