import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Providers from './providers'
import { Toaster } from 'react-hot-toast';
import './globals.scss'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps{
  children: React.ReactNode,
  params: {
    locale: string
  }
}
export default function RootLayout({
  children,
  params: {locale}
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true} className={`${montserrat.className} w-screen overflow-x-hidden`}>
      <Providers>
          {children}
        </Providers>
          <Toaster />
      </body>
    </html>
  )
}
