import type { Metadata } from 'next'
import Providers from './providers'
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps{
  children: React.ReactNode,
  params: {
    locale: string
  }
}
export default function RootLayout({
  children,
  params: {locale}
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true} className="w-screen overflow-x-hidden">
        <Providers>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </Providers>
      </body>
    </html>
  )
}
